# Generated by Django 5.0.7 on 2024-11-09 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tbluser",
            options={"managed": False},
        ),
    ]
