# Generated by Django 5.0.7 on 2024-11-09 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_tbluser_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="tbluser",
            table="tbl_user",
        ),
    ]
